version: "3"

services:
  cache:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=redis12345
      - REDIS_PORT=6379
      - REDIS_DATABASE=0

  db:
    image: postgres:alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=gochat
      - POSTGRES_USER=gochat_admin
      - POSTGRES_PASSWORD=gochat_admin12345

  chat:
    image: gochat-test:v0.0.1
    build:
      context: .
    command: ./chat

    container_name: gochat
    expose:
      - 5050
    ports:
      - 5050:5050
    environment:
      - ENV=local

    depends_on:
      - cache
