version: "3"

services:
  cache:
    image: redis:alpine
    container_name: gochat-cache
    restart: unless-stopped
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=redis12345
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    networks:
      app-network:
        aliases:
          - cache_host
        ipv4_address: 172.0.1.4

  db:
    image: postgres:alpine
    container_name: gochat-db
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - PGDATA=/var/lib/pgsql/data
      - POSTGRES_DB=gochat
      - POSTGRES_USER=gochat_admin
      - POSTGRES_PASSWORD=gochat_admin12345
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gochat_admin", "-d", "gochat"]
      interval: 2s
      timeout: 2s
      retries: 3
    volumes:
      - gochatpgdata:/var/lib/pgsql/data
    networks:
      app-network:
        aliases:
          - db_host
        ipv4_address: 172.0.1.3

  chat:
    build:
      dockerfile: ./Dockerfile

    image: gochat-test:v0.0.1
    container_name: gochat
    restart: unless-stopped

    command: ./chat

    ports:
      - 5050:5050
    environment:
      - ENV=dev
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      app-network:
        ipv4_address: 172.0.1.2

volumes:
  gochatpgdata:

networks:
  app-network:
    name: app-network
    ipam:
      driver: default
      config:
        - subnet: "172.0.1.0/24"
