version: "3"

services:
  cache:
    image: redis:alpine
    container_name: gochat-cache
    restart: always
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=redis12345
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
    # healthcheck:
    #   test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    networks:
      app-network:
        ipv4_address: 172.0.1.4

  db:
    image: postgres:alpine
    container_name: gochat-db
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_DB=gochat
      - POSTGRES_USER=gochat_admin
      - POSTGRES_PASSWORD=gochat_admin12345
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U gochat_admin", "-d gochat"]
    #   interval: 5s
    #   timeout: 2s
    #   retries: 3
    networks:
      app-network:
        ipv4_address: 172.0.1.3

  chat:
    image: gochat-test:v0.0.1
    container_name: gochat
    restart: always

    build:
      context: .
    command: ./chat

    ports:
      - 5050:5050
    environment:
      - ENV=dev
    depends_on:
      - db
      - cache
    networks:
      app-network:
        ipv4_address: 172.0.1.2

networks:
  app-network:
    name: app-network
    ipam:
      driver: default
      config:
        - subnet: "172.0.1.0/24"
