env: "local"
tcp_server:
  addr: "localhost:5050"
  timeout: 5s
  idle_timeout: 60s
storage:
  name: "gochat"
  host: "localhost"
  port: "5432"
  user: "gochat_admin"
  password: "gochat_admin12345"
