env: "local"
tcp_server:
  addr: "localhost:5050"
  timeout: 5s
  idle_timeout: 60s
storage:
  name: "postgres"
  host: "localhost"
  port: "5432"
  user: "gochat-admin"
  password: "gochat-admin12345678"
